version: '3.4'

services:
  tripbooking:
    image: albergo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
